### ISSUE TITLE
Expanding the number of cards for Categories/child categories

### ISSUE THREAD

**Issue by AletaLabak** [denverpost/cannabist#17]
Would it be possible to increase the number of cards that display? Current number is 24 -- is 36 too many? Or whatever number you think makes sense.

Second thought: Is it possible to add a "next page" or "more" option at the bottom of the cards if people wanted to look at more of them?

Here's a note from a reader if it helps with your brainstorming:

Hello,
Excellent Website!
 Scrolling to the bottom of the News page (Colorado for example), there are no stories past Feb.16. Is there some way to access archived and dates before Feb.?
Thanks!

**Comment by schneidan** [comment]
Are we talking about Category (Section) pages here?

**Comment by AletaLabak** [comment]
Yeah, category and child category pages, not the homepage. While I'm at it, do I need to assign these  to you? I was going to, but couldn't figure out a way. But it appears you saw this new issue A-OK.

If you have any ideas on how people can search for older articles, I'm all ears! As we have loaded up on content, the search bar doesn't seem to work as well as it used to. I've been debating whether I should reorganize the category menus, but I didn't want to do anything crazy without consulting with you first.

**Comment by schneidan** [comment]
No, I get emailed when an issue is filed. Joe assigned this one to me, but I'm perfectly happy to self-assign normally. I don't think you can assign since you're not a developer on the repository.

Search bar works the same way, but as you have more content it could be getting slower at least.

I have added pagination to categories' and tags' pages.
